---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hemanager-1.1"
  namespace: "default"
  labels:
    app: "hemanager-1.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hemanager-1.1"
  template:
    metadata:
      labels:
        app: "hemanager-1.1"
    spec:
      containers:
      - name: "hemanager"
        image: "gcr.io/notional-armor-252310/github.com/zegratman/hemanager:$BRANCH_NAME"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hemanager-1-hpa"
  namespace: "default"
  labels:
    app: "hemanager-1.1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hemanager-1.1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
