# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Famille')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='HuileEssentielle',
            fields=[
                ('nom', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Nom')),
                ('nom_alternatif', models.CharField(blank=True, max_length=255, verbose_name='Nom alternatif')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Prix')),
                ('quantite', models.IntegerField(blank=True, choices=[(2, '2 mL'), (5, '5 mL'), (10, '10 mL'), (15, '15 mL'), (20, '20 mL'), (30, '30 mL')], verbose_name='Quantit\xe9')),
                ('prix_bio', models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='Prix bio')),
                ('quantite_bio', models.IntegerField(blank=True, choices=[(2, '2 mL'), (5, '5 mL'), (10, '10 mL'), (15, '15 mL'), (20, '20 mL'), (30, '30 mL')], verbose_name='Quantit\xe9 bio')),
                ('schema', models.ImageField(blank=True, upload_to=b'', verbose_name='Sch\xe9ma')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('famille_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille primaire')),
                ('famille_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille secondaire')),
                ('famille_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille tertiaire')),
                ('famille_4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille annexe 1')),
                ('famille_5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille annexe 2')),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Propri\xe9t\xe9')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteEffective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficacite', models.CharField(choices=[('+', '+'), ('++', '++'), ('+++', '+++'), ('++++', '++++'), ('+++++', '++++++'), ('tout ou rien', 'tout ou rien')], max_length=31, verbose_name='Efficacit\xe9')),
                ('nom_he', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.HuileEssentielle')),
                ('nom_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Propriete')),
            ],
        ),
    ]
