# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='famille_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille secondaire'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='famille_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille tertiaire'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='famille_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille annexe 1'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='famille_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Famille', verbose_name='Famille annexe 2'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='prix_bio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, verbose_name='Prix bio'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='quantite',
            field=models.IntegerField(blank=True, choices=[(2, '2 mL'), (5, '5 mL'), (10, '10 mL'), (15, '15 mL'), (20, '20 mL'), (30, '30 mL')], default=(10, '10 mL'), verbose_name='Quantit\xe9'),
        ),
        migrations.AlterField(
            model_name='huileessentielle',
            name='quantite_bio',
            field=models.IntegerField(blank=True, choices=[(2, '2 mL'), (5, '5 mL'), (10, '10 mL'), (15, '15 mL'), (20, '20 mL'), (30, '30 mL')], default=(10, '10 mL'), verbose_name='Quantit\xe9 bio'),
        ),
    ]
