# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huiles', '0002_auto_20180315_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContreIndication',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ContreIndicationHE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contre_indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.ContreIndication')),
                ('nom_he', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.HuileEssentielle')),
            ],
        ),
    ]
