# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huiles', '0003_contreindication_contreindicationhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom')),
                ('auteur', models.CharField(max_length=255, verbose_name='Auteur')),
                ('year', models.IntegerField(verbose_name='Ann\xe9e')),
            ],
        ),
        migrations.CreateModel(
            name='SourceHE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=255, verbose_name='Pages')),
                ('nom_he', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.HuileEssentielle')),
                ('nom_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Source')),
            ],
        ),
    ]
