# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huiles', '0004_source_sourcehe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteriologie',
            fields=[
                ('identifier', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('huile_essentielle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.HuileEssentielle')),
            ],
        ),
        migrations.CreateModel(
            name='ContreIndicationMaladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contre_indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.ContreIndication')),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteMaladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Maladie')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Propriete')),
            ],
        ),
        migrations.AddField(
            model_name='contreindicationmaladie',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huiles.Maladie'),
        ),
    ]
