# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import huiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('huiles', '0005_auto_20180316_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contreindication',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='huileessentielle',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='propriete',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='huileessentielle',
            name='famille_1_pct',
            field=models.IntegerField(default=0, validators=[huiles.models.percentage_validator], verbose_name='%'),
        ),
        migrations.AddField(
            model_name='huileessentielle',
            name='famille_2_pct',
            field=models.IntegerField(default=0, validators=[huiles.models.percentage_validator], verbose_name='%'),
        ),
        migrations.AddField(
            model_name='huileessentielle',
            name='famille_3_pct',
            field=models.IntegerField(default=0, validators=[huiles.models.percentage_validator], verbose_name='%'),
        ),
        migrations.AddField(
            model_name='huileessentielle',
            name='famille_4_pct',
            field=models.IntegerField(default=0, validators=[huiles.models.percentage_validator], verbose_name='%'),
        ),
        migrations.AddField(
            model_name='huileessentielle',
            name='famille_5_pct',
            field=models.IntegerField(default=0, validators=[huiles.models.percentage_validator], verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='proprieteeffective',
            name='efficacite',
            field=models.CharField(choices=[('+', '+'), ('++', '++'), ('+++', '+++'), ('++++', '++++'), ('+++++', '+++++'), ('tout ou rien', 'tout ou rien')], max_length=31, verbose_name='Efficacit\xe9'),
        ),
    ]
