version: 2
jobs:
  build:
    docker:
      - image: python:2.7-alpine
    branches:
      only:
        - master
        - develop
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t zegratman/hemanager:$TAG .
