version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    branches:
      only:
        - master
        - develop
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - checkout
      - run: echo "A first hello"
